log: True
tail: True

autonomous: True

mongo:
    host: localhost
    port: 27017
    database: bigpaths

start_date: "2012-01-01"
stop_date: "2015-01-01"

bounds:
  NW:
    - -74.053573
    - 40.919423
  SE:
    - -73.699264
    - 40.538534

period_size: 10
grid_size: 6

temperature: 0.25
memory: 32
